### ISSUE TITLE
Reflection not working in SAX parser example

### ISSUE THREAD

**Issue by geoffdigital** [patniemeyer/learningjava#5]
Having a bit of trouble figuring out why the TestSAXModelBuilder doesn't work for me (I pulled the code directly from Github):

Exception in thread "main" org.xml.sax.SAXException: Error: 
java.lang.NoSuchFieldException: animalClass
    at com.oreilly.SAXModelBuilder.startElement(SAXModelBuilder.java:27)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1363)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
    at com.oreilly.TestSAXModelBuilder.main(TestSAXModelBuilder.java:20)
Caused by: java.lang.NoSuchFieldException: animalClass
    at java.lang.Class.getField(Class.java:1584)
    at com.oreilly.SAXModelBuilder.setProperty(SAXModelBuilder.java:56)
    at com.oreilly.SAXModelBuilder.startElement(SAXModelBuilder.java:26)
    ... 11 more

**Comment by geoffdigital** [comment]
Figured it out.  When I placed the code into Eclipse, I gave all the classes a package name "com.oreilly".  I had to add this package name when the classes are created.  The adjusted code is as follows in SAXModelBuilder.java:

20: element = Class.forName("com.oreilly." + className ).newInstance();

There is probably a more elegant way to figure out the package name, but this definitely fixes my problem.
